### ISSUE TITLE
Fluid bladder cannot pick up molten iron from the world

### ISSUE THREAD

**Issue by lxy-unnamed** [W1nter-isHere/FC-Atomic-Space#1]
Change the config ```"Can Pick Up Lava"``` to true in ```config/primal_tech.cfg, line 58```

铁树树苗扔进熔融铁里面会着火弹出来
先扔树苗再倒熔融铁可以正常合成

可以考虑改下水袋的配置
或者用自定义的液体合成铁树树苗避免岩浆属性

**Comment by winterSteve25** [comment]
Fixed, Thanks for your report
