### ISSUE TITLE
Suggestion: allow early access of rain shield

### ISSUE THREAD

**Issue by lxy-unnamed** [W1nter-isHere/FC-Atomic-Space#10]
![image](https://user-images.githubusercontent.com/74656251/100090774-ad244080-2e8e-11eb-8cb6-35e7992b3ed3.png)

Snowing may cause severely low FPS especially when streaming. it would be much better to make rain shield recipe easier and earlier.

**Comment by winterSteve25** [comment]
Thanks, I added a reasonable recipe.
