### ISSUE TITLE
Infinite Gravel/Cobblestone Via Rocks.

### ISSUE THREAD

**Issue by techguy4642** [W1nter-isHere/FC-Atomic-Space#13]
So, when you have a Cobblestone, you can craft it into 4 rocks from the survivalist mod. It takes 3 rocks to make a gravel. But if you put said gravel back into the crafting table, you get 4 rocks. Making for a net gain of 1 rock. And these rocks can be crafted back into more gravel allowing to make more rocks, or into cobblestone. 

![2021-01-05_21 13 51](https://user-images.githubusercontent.com/77035714/103723390-f7293780-4f9f-11eb-9c6b-5c26bfe521ce.png)
![2021-01-05_21 13 55](https://user-images.githubusercontent.com/77035714/103723398-fb555500-4f9f-11eb-868a-6bdc3837cf25.png)
![2021-01-05_21 14 00](https://user-images.githubusercontent.com/77035714/103723401-fd1f1880-4f9f-11eb-91d5-4e8fef3abd85.png)
![2021-01-05_21 14 05](https://user-images.githubusercontent.com/77035714/103723406-fee8dc00-4f9f-11eb-9c84-76e698ffef8f.png)
(No idea if the images work, first time using github for issue reports)

**Comment by winterSteve25** [comment]
Will be fixed in the next update, thank you for your report
