### ISSUE TITLE
TAN Campfire not working as expected

### ISSUE THREAD

**Issue by Ozzymud** [W1nter-isHere/FC-Atomic-Space#14]
Version: Atomic+Space+2.0.1

Crafted/placed/lit a campfire and am standing in the block space right next to it and am still losing heat. Also the torch next to it does nothing as well which seems like it should do /something/.

![2021-01-06_14 11 08](https://user-images.githubusercontent.com/6426344/103824821-82024480-5029-11eb-8b2e-0a17f1ebfeac.png)

**Comment by winterSteve25** [comment]
I think this is just a mod issue

**Comment by Ozzymud** [comment]
Ok, as far as the campfire, it does indeed work. It stops you from getting hpothermia. In Forever Stranded it was set to 15, in this pack 5.. so yea, not very effective.

There are however a bunch of other blocks like the torch that could use some love in block_temperature.json: minecraft:torch, silentgems:stonetorch, primal_tech:fibre_torch_lit, primal_tech:charcoal_hopper, torchmaster:mega_torch, actuallyadditions_block_tiny_torch and darkutils:sneaky_torch

**Comment by winterSteve25** [comment]
Ok, thank you for your suggestions I will add them in the next update
