### ISSUE TITLE
Possible oversight in quests, gunpowder

### ISSUE THREAD

**Issue by Ozzymud** [W1nter-isHere/FC-Atomic-Space#15]
What is the intended way to get gunpowder? Straining gets rotten flesh and bones, fluffy puff crops will get string and you were sneaky enough to give us an emerald as a reward for the market quest which allows the purchase of pumpkin seeds... But when it comes to making the Fel Pumpkin I see no way to acquire gunpowder except for trying to get lucky down in the caves with creepers.  

Am I doing it wrong? I see that later we can crush flint for gunpowder... but I see no Mortar recipe for it. Trying to survive down in the caves before getting some type of warming is almost a death sentence

Also the warming liner comes before the fel pumpkin but requires the blaze powder to make the heating goo/magma blocks. Maybe this is switched around?

**Comment by winterSteve25** [comment]
You can find creepers in the overworld-2464 mantle

**Comment by Ozzymud** [comment]
Yea, without the heating provided by the liners, I was stuck on one heart for quite some time, baby skeletons mixed with that is a bad time. Once able to stay warm and keep health up no worries, but you need the gunpowder to achieve that. Same for the heating packs, need gunpowder to even think about staying warm... it's a chicken and the egg kind of thing.

**Comment by Pandemoneus** [comment]
You don't need to make warm liners using the heating goo method. You can also make the warming liners by crafting the wool armor from Tough as Nails. Then place that armor in the crafting grid one by one and you will get the liners.

Also, as soon as you have the crucible, make lava and place it down. It keeps you warm.
