### ISSUE TITLE
Quest enhancement: Helmet Warm Liner

### ISSUE THREAD

**Issue by Ozzymud** [W1nter-isHere/FC-Atomic-Space#16]
Should add the fact that multiple liners can be added to armor, and later removed as well. You can add a total of 9 protection to armor Helm(2), Chestplate(3) Leggings(3) Boots(1) = Max(9). The only wiki I found also stated that you can use upto 9 and only said 3 on the chestplate... it didn't mention what combo on the other pieces would get you to 9.

This is a total game changer that someone would have to go look up on a wiki, seems better if it were at least mentioned in the quests.

**Comment by winterSteve25** [comment]
Will do, thank you :)

**Comment by winterSteve25** [comment]
Will be fixed, thank you for your report
