### ISSUE TITLE
Natural health regen not happening, but saturation depletes when thirsty

### ISSUE THREAD

**Issue by Ozzymud** [W1nter-isHere/FC-Atomic-Space#17]
If thirsty and not healed completely, topping off food/saturation uses ALL saturation as if it were healing you, but you get nothing from it.

Steps:

Don't be full of water (more then one drop down)
Take some damage
Either already have saturation up or eat something to do so
Watch as saturation decreases rapidly but no health is returned
Drinking until full allows regenning of health as normal.

Expected results: not using saturation if it isn't going to heal me when thirsty.

**Comment by winterSteve25** [comment]
It is how the mod intended to work.
