### ISSUE TITLE
Staging issue on Hopping Bonsai Pot

### ISSUE THREAD

**Issue by Ozzymud** [W1nter-isHere/FC-Atomic-Space#19]
Was finally able to make the hopper and excitedly made the hopping bonsai pot only to realize it was an unknown item even though the quest had me make it.

![image1](https://user-images.githubusercontent.com/6426344/103855536-c6143a00-5067-11eb-929a-b65749c90aca.png)

![image1](https://user-images.githubusercontent.com/6426344/103855691-125f7a00-5068-11eb-8485-4da22a846315.png)

**Comment by winterSteve25** [comment]
It's not a staging issue, I made it that you need to do some research before you can use it. It's a quest issue. Thank you for the report

**Comment by winterSteve25** [comment]
It will be fixed in the next update. Thank you for your report.
