### ISSUE TITLE
Rotten flesh in drying rack eventually became tanned leather

### ISSUE THREAD

**Issue by lxy-unnamed** [W1nter-isHere/FC-Atomic-Space#2]
![image](https://user-images.githubusercontent.com/74656251/99806521-19dec880-2b79-11eb-87f5-5e037b6762f9.png)
![image](https://user-images.githubusercontent.com/74656251/99806550-219e6d00-2b79-11eb-8ada-8c7e106250ec.png)
 I don't know whether it is intentional or not. Really a huge waste of resource in early game if you forgot to take the leather out in time.

Tanned leather are only used in tanned leather armor recipe so maybe you could delete the tanned leather recipe?

**Comment by winterSteve25** [comment]
Ok, I will look into that thanks for your report!

**Comment by winterSteve25** [comment]
Fixed
