### ISSUE TITLE
Portable Generator doesn't accept gasoline

### ISSUE THREAD

**Issue by Ozzymud** [W1nter-isHere/FC-Atomic-Space#21]
Been trying to get some gas into the portable generator i crafted. Tried vanilla buckets the Immersive manual mentioned, a jerry can(16iron), and a transfer node from extra utilities, nothing will put gas into the generator.

**Comment by winterSteve25** [comment]
You are not suppose to use the portable generator. The recipe for that machine will be removed in the next version. Thanks for your report.
