### ISSUE TITLE
Issue/Crash between Immersive Engineering and NuclearCraft when breaking IE fluid pipes

### ISSUE THREAD

**Issue by Pandemoneus** [W1nter-isHere/FC-Atomic-Space#22]
Description:
When breaking Immersive Engineering fluid pipes, several issues appear:
1. The pipe does not drop
2. In the top right, a popup shows that there was an issue with NuclearCraft and Immersive Engineering
3. When contiunously breaking pipes, the server crashes and you end back in the main menu.

Steps to reproduce:
1. Place Immersive Engineering fluid pipes.
2. Break fluid pipes using a pickaxe.

What should have happened:
1. Pipes drop normally
2. No errors should pop up

Error log:
[crash-2021-01-06_20.44.14-server.txt](https://github.com/W1nter-isHere/FC-Atomic-Space/files/5786821/crash-2021-01-06_20.44.14-server.txt)

**Comment by winterSteve25** [comment]
Thank you for your report. But please use gist or pastebin or something like that next time

**Comment by winterSteve25** [comment]
The pipe will be removed in the next version, use fluids laser rely instead.

**Comment by Pandemoneus** [comment]
Note: Make sure pipes are still craftable and placeable, since some IE multiblocks need pipes to be assembled.

**Comment by winterSteve25** [comment]
Good point

**Comment by Pandemoneus** [comment]
Maybe you can exclude IE pipes from radiation via
**nuclearcraft.cfg**
    S:radiation_blocks_blacklist <
     >

That might fix the bug.

**Comment by winterSteve25** [comment]
Hmmm, interesting, I will try that
