### ISSUE TITLE
No crystal growth accelerators for pure certus quartz in chapter 4

### ISSUE THREAD

**Issue by Pandemoneus** [W1nter-isHere/FC-Atomic-Space#23]
I am not sure whether that is intended, but pure certus quartz cannot be 'reasonably' crafted in chapter 4. You can craft certus quartz seeds, but you cannot craft the crystal growth accelerators. It will take hours of the seeds to grow in water without them.
The stage 'Advanced Automation' is locked behind the chapter 5 research. However, in chapter 4, you have to craft Mekanism basic control circuits, which require printed calculating processors which require pure certus quartz.

[edit]
You can craft crystal growth accelerators, but you cannot place them.

**Comment by winterSteve25** [comment]
Ok thank you for your report, it will be fixed in the next update.
