### ISSUE TITLE
mana input hatch needs Hopperhock ==>

### ISSUE THREAD

**Issue by BugsReporter9000** [W1nter-isHere/FC-Atomic-Space#25]
Hi 
i'm trying to make the flux manafield to generate Mana . it needs a Mana output hatch which is made from Mana input hatch via a chisel . the Mana input hatch need hopperhock flower which can be made in the industrial petal apothecary using a ( rune of air ) 
which needs Mana to be created in the runic altar . 

chicken and egg problem i guess .

**Comment by W1nter-isHere** [comment]
Ok thank you for the report, I will look into the problem.

**Comment by W1nter-isHere** [comment]
It will be fixed in the next update :)
