### ISSUE TITLE
Lazy AE2 broken recipes

### ISSUE THREAD

**Issue by BugsReporter9000** [W1nter-isHere/FC-Atomic-Space#26]
hi ,
to be able to make a Lazy AE2 machines you need Fluix Logic Unit that needs speculative processor 
which can not be made without a Lazy AE2 machine . 

i think all the Lazy AE2 recipes need revision .

thanks

**Comment by W1nter-isHere** [comment]
Did you check the new update? It require an etcher and an aggregator in order to craft the fluix logic unit, and these 2 machine recipes has been changed in the latest update (released a couple hours ago).

**Comment by BugsReporter9000** [comment]
haven't updated yet , ill check it out . thanks

**Comment by W1nter-isHere** [comment]
Yea, no problem

**Comment by BugsReporter9000** [comment]
fixed , thx
