### ISSUE TITLE
Overworld -2464 Core Portal 

### ISSUE THREAD

**Issue by BugsReporter9000** [W1nter-isHere/FC-Atomic-Space#27]
hi again 

i made the metal alloy port key , but how exactly do i go to the dimension ?

**Comment by W1nter-isHere** [comment]
Same thing you did for the mantle, go to the bedrock of mantle use the port key shift right click bedrock

**Comment by W1nter-isHere** [comment]
@BugsReporter9000 for these simple questions, you can come over to our discord and ask us overthere :)
