### ISSUE TITLE
Non-vanilla ores in mantle do not work properly

### ISSUE THREAD

**Issue by Lee65535** [W1nter-isHere/FC-Atomic-Space#30]
Version: 2.0.4
While JEI tells me that they are ores, these blocks look exactly the same as regular icy stone, and mining them gets me permafrost;
This happens both in single player world and in dedicated server, and both on naturally generated ores and ones placed by players
![2021-02-02_19 20 23](https://user-images.githubusercontent.com/36479623/106594119-a26fe100-658c-11eb-90f5-47bb5a82f12f.png)
![2021-02-02_19 20 30](https://user-images.githubusercontent.com/36479623/106594125-a439a480-658c-11eb-9be6-34fde578714d.png)
![2021-02-02_19 20 46](https://user-images.githubusercontent.com/36479623/106594137-a7349500-658c-11eb-8c36-9bdfbb67c282.png)
![2021-02-02_19 20 50](https://user-images.githubusercontent.com/36479623/106594140-a865c200-658c-11eb-9abe-152373478603.png)

**Comment by winterSteve25** [comment]
This is how I intended it to work. You can not see it because you have not unlocked the required stage yet
