### ISSUE TITLE
Ironwood tree cannot be accelerated growing with dancing

### ISSUE THREAD

**Issue by lxy-unnamed** [W1nter-isHere/FC-Atomic-Space#4]
Rustic saplings was not recognized as saplings by Twerk Sim 2k16.

Manually adding ```rustic:sapling``` to whitelist in ```config/ts2k16.cfg, Line 29``` would make things work.
```
    # Additional plants that can be affected (Case Sensitive) [default: ]
    S:Whitelist <
        rustic:sapling
     >

```

**Comment by winterSteve25** [comment]
Ok thanks for the report
