### ISSUE TITLE
im lagging

### ISSUE THREAD

**Issue by alexvaboe** [W1nter-isHere/FC-Atomic-Space#43]
hi i dont know why it looks like im having random lag spikes.  it happen when i mine. it happen when im placing stuff. 
help

**Comment by alexvaboe** [comment]
and other random times i dont remember

**Comment by winterSteve25** [comment]
What version of the pack are you on? Because it is known as an issue in a few early versions of the pack

**Comment by alexvaboe** [comment]
2.1.4
and why is the pack using 11-12gb ram??

**Comment by winterSteve25** [comment]
It shouldnt, I dev it using 6gs and it works fine, can you provide the log?

**Comment by alexvaboe** [comment]
how do i do that?

**Comment by alexvaboe** [comment]
[latest.log](https://github.com/FictionCraft-Team/FC-Atomic-Space/files/6394133/latest.log)

**Comment by alexvaboe** [comment]
is this it?

**Comment by winterSteve25** [comment]
yep, lol i was gonna explain it

**Comment by winterSteve25** [comment]
try disabling/removing the _dynamic lights_ mod

**Comment by alexvaboe** [comment]
fixed lagg spike.  but its still using 12-13 gb ram

**Comment by winterSteve25** [comment]
hmmm are you using a high-resolution texture pack or something?

**Comment by alexvaboe** [comment]
nah default

**Comment by winterSteve25** [comment]
I am not sure then, there is nothing unusual in the log, I will let you know if I find anything
