### ISSUE TITLE
2.1.4 - Item Description Inscriber Press 

### ISSUE THREAD

**Issue by Aringarosa** [W1nter-isHere/FC-Atomic-Space#45]
Hey FC-Team,

This belongs in the "I was confused" section.

The Description of "Inscriber Silicon Press" tells the alternate crafting process correctly. 
![image](https://user-images.githubusercontent.com/5900536/119248535-0ea13f80-bb92-11eb-8158-2aac7e258450.png)

The other three do tell both way's. The alternate and the normal. 
![image](https://user-images.githubusercontent.com/5900536/119248602-90916880-bb92-11eb-9086-f89c09178f4f.png)

Unfortunately, it first shows the "normal" route and then the alternative.
I hadn't even noticed that there are two descriptions and accordingly hiked unsuccessfully through the ice desert.
can you switch off the original tooltip there?

Greetings Ringo

**Comment by winterSteve25** [comment]
Thanks for reaching out Ringo,

Unfortunately there is no way for us to remove a jei description,we have asked the developer of JEI (mezz) and they said it is not possible to remove jei description.

Sorry for the confusion and inconvenience

winterSteve25

**Comment by Aringarosa** [comment]
Unfortunate yes, but that's the way it is.
Thanks for the reply. Case closed!

p.s.: Real good work with this Pack!
