### ISSUE TITLE
2.1.4 - TorchMaster + StoneTorch

### ISSUE THREAD

**Issue by Aringarosa** [W1nter-isHere/FC-Atomic-Space#49]
Heyho Winter,

I think I found a little bug there. The Terrain Lighter from "TorchMaster" do not accept Stone Torches from "Silent's gems" .

Feature as intended or Oversight? Can be configured in the Config of "Torchmaster"
standart:
```
 S:TerrainLighterTorches <
         minecraft:torch
         tconstruct:stone_torch
      >
```

with Sient's gems Torch
```
    S:TerrainLighterTorches <
        minecraft:torch
        tconstruct:stone_torch
        silentgems:stonetorch
     >
```

greetings Ringo

**Comment by winterSteve25** [comment]
Sorry for late reply, will fix.
