### ISSUE TITLE
2.1.4 - Certus Quartz / Charged Certus Quartz Ore

### ISSUE THREAD

**Issue by Aringarosa** [W1nter-isHere/FC-Atomic-Space#50]
Good Morning,

I was on the hunt for charged Certus quartz and stumbled across an inconsistency in staging.

The ores "Certus Quartz" and "Charged Certus Quartz" already spawn with the research Capter_3. The item description for the ores says but you need the "automation_advanced" research.

![image](https://user-images.githubusercontent.com/5900536/120137928-abd52700-c1d5-11eb-9019-6739b4f512d2.png)

Greetings Ringo

**Comment by winterSteve25** [comment]
Sorry for late reply, will fix.
