### ISSUE TITLE
Server crash when craft dense_crystal_rad using SoulBinder

### ISSUE THREAD

**Issue by SeaLoong** [W1nter-isHere/FC-Atomic-Space#52]
[Crash log](https://gist.github.com/SeaLoong/ad4c5101329ea327b7e6f24ad310e8b4)

The reason is that the value of liquid XP is overflow which is computed from 10000 level XP
After crash, the save can't be load. Once load the save, it crashs again.

My solution is modify the config file
`scripts\mod\crafttweaker\enderio\soul_binder.zs`
```
import mods.enderio.SoulBinder;
//Radioactive crystal
mods.enderio.SoulBinder.addRecipe(
	<contenttweaker:dense_crystal_rad>,
	<contenttweaker:dense_crystal>,
	["nuclearcraft:feral_ghoul"],
	1000,   // it is energyCost, not XP! See below
	10000 // it is XP! should be modified to a value less than 1000(I guess), I modified it to 10
);
//Drop of Evil
mods.enderio.SoulBinder.addRecipe(
	<extrautils2:ingredients:10>,
	<minecraft:ghast_tear>,
	["minecraft:wither_skeleton"],
	1000,
	10000 // same
);
//nickel chicken
mods.enderio.SoulBinder.addRecipe(
	<roost:chicken>.withTag({Growth: 1, Chicken: "morechickens:nickelchicken", Gain: 1, Strength: 1}),
	<thermalfoundation:storage:5> *64,
	["chickens:smartchicken"],
	1000,
	500000 // same
);
```
 [EnderTweaker Documentation](https://github.com/Shadows-of-Fire/EnderTweaker/blob/master/Documentation.md) and the issue [Typo](https://github.com/Shadows-of-Fire/EnderTweaker/issues/15) 
The mistake in source code: [SoulBinder](https://github.com/Shadows-of-Fire/EnderTweaker/blob/master/src/main/java/shadows/endertweaker/SoulBinder.java#L30) [SoulBinderRecipe](https://github.com/Shadows-of-Fire/EnderTweaker/blob/master/src/main/java/shadows/endertweaker/recipe/SoulBinderRecipe.java#L17)

**Comment by winterSteve25** [comment]
Thanks for repoting. Will fix.
