### ISSUE TITLE
Artisan Automation's Tool Repair Upgrades do not work.

### ISSUE THREAD

**Issue by ginyai** [W1nter-isHere/FC-Atomic-Space#53]
https://github.com/FictionCraft-Team/FC-Atomic-Space/blob/b31c8e46da9cd5f10f89404e9516bee7188c6f20/scripts/mod/crafttweaker/artisan_items.zs#L230-L242
The `DurabilityRepaired` should be between 0 and 1.
https://artisan-automation.readthedocs.io/en/latest/upgrades/#tool-repair-upgrades

**Comment by winterSteve25** [comment]
Thanks, I thought I fixed it, must have overlooked. Will fix
