### ISSUE TITLE
发生冲突

### ISSUE THREAD

**Issue by sittis1** [W1nter-isHere/FC-Atomic-Space#55]
[错误报告-2021-11-3_19.36.23.zip](https://github.com/FictionCraft-Team/FC-Atomic-Space/files/7474359/-2021-11-3_19.36.23.zip)

**Comment by winterSteve25** [comment]
请用pastebin或类似发送崩溃报告

**Comment by sittis1** [comment]
[https://pastebin.com/P9G02sZ3](url)

**Comment by sittis1** [comment]
https://pastebin.com/P9G02sZ3

**Comment by sittis1** [comment]
https://pastebin.com/Wkzti2yf
崩溃操作是
搭好模块化机器（用电子，质子，，合成锭的那个）
机械控制器识别出变色后就崩溃了
希望作者大大能帮帮解决，谢谢了

**Comment by winterSteve25** [comment]
已修复
