### ISSUE TITLE
Aluminum amber shouldn't be smelt into aluminum ingot

### ISSUE THREAD

**Issue by lxy-unnamed** [W1nter-isHere/FC-Atomic-Space#9]
It should be processed in the blast furnace only
![image](https://user-images.githubusercontent.com/74656251/100090286-ed36f380-2e8d-11eb-8528-9376fb53185e.png)
![image](https://user-images.githubusercontent.com/74656251/100090379-0d66b280-2e8e-11eb-8e09-605a3bb57a01.png)

**Comment by winterSteve25** [comment]
Thanks, fixed
